//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Исходное имя файла:
// Дата создания: 31.03.2022 23:23:11
namespace DB
{
    
    /// <summary>
    /// В схеме отсутствуют комментарии для TelefonModel.Abonent.
    /// </summary>
    /// <KeyProperties>
    /// Number
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TelefonModel", Name="Abonent")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Abonent : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Создайте новый объект Abonent.
        /// </summary>
        /// <param name="number">Начальное значение Number.</param>
        /// <param name="lastName">Начальное значение LastName.</param>
        /// <param name="firstName">Начальное значение FirstName.</param>
        /// <param name="datePayment">Начальное значение DatePayment.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Abonent CreateAbonent(int number, string lastName, string firstName, global::System.DateTime datePayment)
        {
            Abonent abonent = new Abonent();
            abonent.Number = number;
            abonent.LastName = lastName;
            abonent.FirstName = firstName;
            abonent.DatePayment = datePayment;
            return abonent;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Number.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this.ReportPropertyChanging("Number");
                this._Number = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Number");
                this.OnNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Number;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNumberChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNumberChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства LastName.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this.ReportPropertyChanging("LastName");
                this._LastName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LastName");
                this.OnLastNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _LastName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLastNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLastNameChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства FirstName.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this.ReportPropertyChanging("FirstName");
                this._FirstName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FirstName");
                this.OnFirstNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _FirstName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFirstNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFirstNameChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства DatePayment.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime DatePayment
        {
            get
            {
                return this._DatePayment;
            }
            set
            {
                this.OnDatePaymentChanging(value);
                this.ReportPropertyChanging("DatePayment");
                this._DatePayment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DatePayment");
                this.OnDatePaymentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _DatePayment;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDatePaymentChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDatePaymentChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Payment.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<double> Payment
        {
            get
            {
                return this._Payment;
            }
            set
            {
                this.OnPaymentChanging(value);
                this.ReportPropertyChanging("Payment");
                this._Payment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Payment");
                this.OnPaymentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<double> _Payment;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPaymentChanging(global::System.Nullable<double> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPaymentChanged();
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для TelefonEntities.
    /// </summary>
    public partial class TelefonEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Инициализирует новый объект TelefonEntities, используя строку соединения из раздела "TelefonEntities" файла конфигурации приложения.
        /// </summary>
        public TelefonEntities() : 
                base("name=TelefonEntities", "TelefonEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Инициализируйте новый объект TelefonEntities.
        /// </summary>
        public TelefonEntities(string connectionString) : 
                base(connectionString, "TelefonEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Инициализируйте новый объект TelefonEntities.
        /// </summary>
        public TelefonEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TelefonEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// В схеме отсутствуют комментарии для Abonent.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Abonent> Abonent
        {
            get
            {
                if ((this._Abonent == null))
                {
                    this._Abonent = base.CreateQuery<Abonent>("[Abonent]");
                }
                return this._Abonent;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Abonent> _Abonent;
        /// <summary>
        /// В схеме отсутствуют комментарии для Abonent.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToAbonent(Abonent abonent)
        {
            base.AddObject("Abonent", abonent);
        }
    }
}
