//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Podgotovka.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int userID { get; set; }
        public string userSurname { get; set; }
        public string userName { get; set; }
        public string userPatronymic { get; set; }
        public string userLogin { get; set; }
        public string userPassword { get; set; }
        public int userRole { get; set; }
    
        public virtual StaffRole StaffRole { get; set; }
    }
}
