//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClubForsaj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessClubForsajEntities : DbContext
    {
        public FitnessClubForsajEntities()
            : base("name=FitnessClubForsajEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<ClassTypes> ClassTypes { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Memberships> Memberships { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Trainers> Trainers { get; set; }
        public virtual DbSet<VisitHistory> VisitHistory { get; set; }
    }
}
