//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClubForsaj
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitHistory
    {
        public int VisitID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public System.DateTime VisitDate { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
