//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppVetclinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.orderProducts = new HashSet<orderProducts>();
        }
    
        public int orderID { get; set; }
        public Nullable<int> stuffID { get; set; }
        public Nullable<int> userID { get; set; }
        public System.DateTime orderDate { get; set; }
        public decimal orderCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderProducts> orderProducts { get; set; }
        public virtual Stuffs Stuffs { get; set; }
        public virtual Users Users { get; set; }
    }
}
